services:
  caddy:
    image: caddy:2-alpine
    container_name: stock-proxy-master
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites-enabled:/etc/caddy/sites-enabled
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - stock-proxy-net

networks:
  stock-proxy-net:
    name: stocksystem-proxy-net
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
